[project]
name = "deep-learning-3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.09"
dependencies = [
    "ipykernel>=6.29.5",
    "numpy==1.21.6",
    "pybind11>=2.13.6",
    "tensorflow==2.9",
    "tensorflow-io-gcs-filesystem==0.27.0",
]
